// This file is automatically generated. Do not edit it directly.
// Using stub implementation while backend is being built
import { supabase } from '@/lib/supabaseStub';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export { supabase };

